name: qiita-adc-d-20211124
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.097.2
    - name: 'Test Markdown'
      run: |
        dub run md --compiler=$DC -- articles/qiita-adc-d-20211224.md