name: qiita-adc-d-20211124
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
    - name: 'Test Markdown'
      run: |
        dub run md --compiler=$DC -- articles/qiita-adc-d-20211224.md